---
name: PDF compilation
on: workflow_dispatch
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello, world!"
  devops_ru_2pages:
    runs-on: ubuntu-latest
    steps:
      - name: Getting codebase
        uses: actions/checkout@v4
      - name: Show files
        run: |
          pwd
          find .
      - name: Compilation
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            devops_ru_2pages.tex
          working_directory: |
            devops_ru_2pages
      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: devops_ru_2pages
          path: devops_ru_2pages.pdf
