---
name: PDF compilation
on:
  workflow_dispatch:
  workflow_call:
jobs:
  Build_PDFs:
    runs-on: ubuntu-latest
    steps:
      - name: Getting DevOps CV codebase
        uses: actions/checkout@v4
        with:
          ref: 'devops_ru_2pages'
      - name: Compilation
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
      - name: Rename result file
        run: mv cv.pdf devops_ru_2pages.pdf
      - name: Show file
        run: find *.pdf
      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: devops_ru_2pages
          path: |
            devops_ru_2pages.pdf
          retention-days: 30
          if-no-files-found: error
      - name: Getting DataEngineer CV codebase
        uses: actions/checkout@v4
        with:
          ref: 'dataengineer_en_2pages'
      - name: Compilation
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
      - name: Rename result file
        run: mv cv.pdf dataengineer_en_2pages.pdf
      - name: Show file
        run: find *.pdf
      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dataengineer_en_2pages
          path: |
            dataengineer_en_2pages.pdf
          retention-days: 30
          if-no-files-found: error
